sudo: false
dist: trusty

language: php
php: 7.1

env:
  global:
    - WP_CLI_BIN_DIR=/tmp/wp-cli-phar
    - TEST_COMMANDS=0
    - TEST_COMMANDS_GLOB=*-command

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - ./ci/prepare.sh

after_script:
  - ls -laR $HOME/.composer/cache

jobs:
  include:
    - stage: sniff
      script: ./ci/sniff.sh
      env: BUILD=sniff
    - stage: test
      script: ./ci/test.sh
      php: 7.0
      env: WP_VERSION=latest WP_CLI_TEST_LOG_RUN_TIMES='stdout,40,40'

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - master
    - /^release-.+$/

notifications:
  email:
    on_success: never
    on_failure: change
